<?php

/**
 * @file
 * Campaign module help and theme functions.
 */

/**
 * Implements hook_theme().
 */
function campaign_theme($existing, $type, $theme, $path) {
  
  	return [
	    'campaign' => [
	      	'variables' => [
	      		'campaign' => []
	      	],
	      	'template' => 'campaign',
	    ],
		'campaignDetails' => [
		    'variables' => [
			    'campaignDetails' => []
			],
            'template' => 'campaign-details',
		],
		'campaignList' => [
		    'variables' => [
				'campaignList' => []
			],
            'template' => 'campaign-list',
		],
	];
}